export interface Programme {
  id: string;
  title: string;
  description: string;
  duration: string;
  level: "B1+" | "B2" | "B2+" | "C1" | "C1+" | "C2";
  sessions: number;
  status: "available" | "coming_soon" | "locked";
  icon: string;
  isNew?: boolean;
  isFlagship?: boolean;
}

export interface Segment {
  id: string;
  number: number;
  name: string;
  tagline: string;
  description: string;
  color: string;
  icon: string;
  programmes: Programme[];
}

export const segmentsData: Segment[] = [
  {
    id: "perform",
    number: 1,
    name: "PERFORM",
    tagline: "Be Stronger in the Room",
    description: "Programmes for executives who need to hold authority under pressure.",
    color: "#B89A5A",
    icon: "Zap",
    programmes: [
      {
        id: "exec-comm-performance",
        title: "Executive Communication Performance Program",
        description: "The 10-session flagship programme. Master authority, presence, and persuasion in high-stakes executive environments.",
        duration: "10 weeks",
        level: "B2+",
        sessions: 10,
        status: "available",
        icon: "Star",
        isFlagship: true,
      },
      {
        id: "crisis-communication",
        title: "Crisis Communication",
        description: "Address the board, your team, or the media during emergencies with clarity and composure.",
        duration: "4 weeks",
        level: "C1",
        sessions: 4,
        status: "coming_soon",
        icon: "AlertTriangle",
      },
      {
        id: "stakeholder-management",
        title: "Stakeholder Management",
        description: "Navigate meetings with conflicting interests and steer outcomes with diplomatic precision.",
        duration: "4 weeks",
        level: "C1",
        sessions: 4,
        status: "coming_soon",
        icon: "Users",
      },
      {
        id: "upward-communication",
        title: "Upward Communication",
        description: "Present bad news, challenge decisions, or push back effectively against CEO and board level.",
        duration: "3 weeks",
        level: "C1+",
        sessions: 3,
        status: "coming_soon",
        icon: "TrendingUp",
      },
      {
        id: "hostile-audience",
        title: "The Hostile Audience",
        description: "Present confidently to a room that disagrees with you and win them over.",
        duration: "3 weeks",
        level: "C1+",
        sessions: 3,
        status: "coming_soon",
        icon: "Shield",
      },
      {
        id: "cross-cultural-boardroom",
        title: "Cross-Cultural Boardroom Dynamics",
        description: "Handle rooms with different cultural communication styles and adapt in real time.",
        duration: "4 weeks",
        level: "C1",
        sessions: 4,
        status: "coming_soon",
        icon: "Globe",
      },
    ],
  },
  {
    id: "my-market",
    number: 2,
    name: "MY MARKET",
    tagline: "Master Your Industry",
    description: "Industry-specific vocabulary and real-world scenario packs.",
    color: "#6B8FBF",
    icon: "Briefcase",
    programmes: [
      {
        id: "tech-saas",
        title: "Tech / SaaS",
        description: "Speak the language of product, engineering, and growth metrics in international tech environments.",
        duration: "3 weeks",
        level: "B2",
        sessions: 3,
        status: "coming_soon",
        icon: "Monitor",
      },
      {
        id: "finance-banking",
        title: "Finance / Banking",
        description: "Command boardrooms with financial vocabulary, deal language, and investor communication.",
        duration: "3 weeks",
        level: "B2+",
        sessions: 3,
        status: "coming_soon",
        icon: "BarChart2",
      },
      {
        id: "pharma-healthcare",
        title: "Pharmaceuticals / Healthcare",
        description: "Navigate regulatory language, clinical terminology, and stakeholder communication in life sciences.",
        duration: "3 weeks",
        level: "B2",
        sessions: 3,
        status: "coming_soon",
        icon: "Heart",
      },
      {
        id: "real-estate",
        title: "Real Estate",
        description: "Discuss property, development, and investment with precision and authority.",
        duration: "2 weeks",
        level: "B2",
        sessions: 2,
        status: "coming_soon",
        icon: "Home",
      },
      {
        id: "energy",
        title: "Energy",
        description: "Communicate confidently in oil & gas, renewables, and energy transition contexts.",
        duration: "3 weeks",
        level: "B2",
        sessions: 3,
        status: "coming_soon",
        icon: "Zap",
      },
      {
        id: "manufacturing-engineering",
        title: "Manufacturing / Engineering",
        description: "Operational language, supply chain terminology, and technical presentations.",
        duration: "3 weeks",
        level: "B2",
        sessions: 3,
        status: "coming_soon",
        icon: "Settings",
      },
      {
        id: "insurance",
        title: "Insurance",
        description: "Policy language, risk communication, and client advisory vocabulary.",
        duration: "2 weeks",
        level: "B2",
        sessions: 2,
        status: "coming_soon",
        icon: "FileCheck",
      },
      {
        id: "hr-people",
        title: "HR / People",
        description: "Talent conversations, performance language, and organisational communication.",
        duration: "2 weeks",
        level: "B2",
        sessions: 2,
        status: "coming_soon",
        icon: "UserCheck",
      },
      {
        id: "legal-compliance",
        title: "Legal / Compliance",
        description: "Formal legal language, compliance communication, and contract vocabulary.",
        duration: "3 weeks",
        level: "C1",
        sessions: 3,
        status: "coming_soon",
        icon: "Scale",
      },
      {
        id: "procurement-supply-chain",
        title: "Procurement / Supply Chain",
        description: "Negotiate, manage vendors, and communicate operational challenges in international contexts.",
        duration: "3 weeks",
        level: "B2",
        sessions: 3,
        status: "coming_soon",
        icon: "Package",
      },
    ],
  },
  {
    id: "communicate",
    number: 3,
    name: "COMMUNICATE",
    tagline: "Deliver Your Message",
    description: "Master every format of executive communication.",
    color: "#7B9E6B",
    icon: "MessageSquare",
    programmes: [
      {
        id: "presentation-command",
        title: "Presentation Command",
        description: "Structure, deliver, and own any presentation — from board slides to TED-style talks.",
        duration: "5 weeks",
        level: "B2+",
        sessions: 5,
        status: "available",
        icon: "Presentation",
        isNew: true,
      },
      {
        id: "sales-client-management",
        title: "Sales & Client Management",
        description: "Pitch, negotiate, and manage client relationships with executive-level communication.",
        duration: "4 weeks",
        level: "B2",
        sessions: 4,
        status: "coming_soon",
        icon: "Handshake",
      },
      {
        id: "storytelling",
        title: "Storytelling",
        description: "Use narrative frameworks to make data, strategy, and change compelling.",
        duration: "3 weeks",
        level: "B2+",
        sessions: 3,
        status: "coming_soon",
        icon: "BookOpen",
      },
      {
        id: "writing-lab",
        title: "Writing Lab",
        description: "Write executive emails, reports, and memos that get read, respected, and acted on.",
        duration: "4 weeks",
        level: "B2",
        sessions: 4,
        status: "available",
        icon: "PenLine",
        isNew: true,
      },
      {
        id: "numbers-financial-data",
        title: "Numbers & Financial Data",
        description: "Present financial data, explain KPIs, and discuss budgets with authority.",
        duration: "3 weeks",
        level: "B2+",
        sessions: 3,
        status: "coming_soon",
        icon: "Calculator",
      },
      {
        id: "business-language",
        title: "Business Language (Cross-Functional)",
        description: "Master the vocabulary that crosses departments — from ops to strategy to marketing.",
        duration: "3 weeks",
        level: "B2",
        sessions: 3,
        status: "coming_soon",
        icon: "Languages",
      },
    ],
  },
  {
    id: "understand",
    number: 4,
    name: "UNDERSTAND",
    tagline: "Read the Room, Hear the World",
    description: "Sharpen your ability to decode accents, culture, and context.",
    color: "#9B7BB5",
    icon: "Ear",
    programmes: [
      {
        id: "accent-navigator",
        title: "Accent Navigator / Listening Lab",
        description: "Train your ear to understand native speakers from the UK, US, Ireland, India, and beyond.",
        duration: "4 weeks",
        level: "B1+",
        sessions: 4,
        status: "coming_soon",
        icon: "Headphones",
      },
      {
        id: "cultural-decoder",
        title: "Cultural Decoder",
        description: "Understand unspoken communication norms in British, American, and Asian business culture.",
        duration: "3 weeks",
        level: "B2",
        sessions: 3,
        status: "coming_soon",
        icon: "Globe2",
      },
      {
        id: "pronunciation-clinic",
        title: "Pronunciation Clinic",
        description: "Neutralise your accent where it causes misunderstanding and build confident vocal delivery.",
        duration: "4 weeks",
        level: "B2",
        sessions: 4,
        status: "coming_soon",
        icon: "Mic",
      },
      {
        id: "remote-leadership",
        title: "Remote Leadership",
        description: "Communicate with authority and warmth in virtual meetings, async updates, and distributed teams.",
        duration: "3 weeks",
        level: "B2+",
        sessions: 3,
        status: "coming_soon",
        icon: "Video",
      },
    ],
  },
  {
    id: "grow",
    number: 5,
    name: "GROW",
    tagline: "Develop as a Leader",
    description: "Build the personal and professional dimensions of executive presence.",
    color: "#BF8B5A",
    icon: "Sprout",
    programmes: [
      {
        id: "leadership-self-development",
        title: "Leadership & Self-Development",
        description: "Articulate your vision, lead difficult conversations, and build your executive identity.",
        duration: "5 weeks",
        level: "C1",
        sessions: 5,
        status: "coming_soon",
        icon: "Crown",
      },
      {
        id: "social-english",
        title: "Social English",
        description: "Master small talk, networking events, dinners, and informal executive interactions.",
        duration: "3 weeks",
        level: "B2",
        sessions: 3,
        status: "coming_soon",
        icon: "Coffee",
      },
      {
        id: "executive-book-club",
        title: "Executive Book Club",
        description: "Discuss leadership books, extract insights, and build your intellectual vocabulary.",
        duration: "Ongoing",
        level: "C1",
        sessions: 6,
        status: "coming_soon",
        icon: "BookMarked",
      },
    ],
  },
  {
    id: "prepare",
    number: 6,
    name: "PREPARE",
    tagline: "Handle What is Coming",
    description: "Get ready for the specific challenges ahead.",
    color: "#BF5A5A",
    icon: "Target",
    programmes: [
      {
        id: "interview-preparation",
        title: "Interview Preparation",
        description: "Prepare for C-suite interviews, board interviews, and executive assessment centres.",
        duration: "4 weeks",
        level: "C1",
        sessions: 4,
        status: "available",
        icon: "ClipboardCheck",
        isNew: true,
      },
      {
        id: "expat-survival",
        title: "Expat Survival",
        description: "Navigate the practical and cultural language challenges of relocating for work.",
        duration: "3 weeks",
        level: "B2",
        sessions: 3,
        status: "coming_soon",
        icon: "MapPin",
      },
    ],
  },
  {
    id: "stay-sharp",
    number: 7,
    name: "STAY SHARP",
    tagline: "Stay Connected to the Market",
    description: "Keep your language and thinking current with what's happening in business.",
    color: "#5A9BBF",
    icon: "Radar",
    programmes: [
      {
        id: "linkedin-intelligence",
        title: "LinkedIn Intelligence",
        description: "Write posts, engage professionally, and build your personal brand in English.",
        duration: "2 weeks",
        level: "B2",
        sessions: 2,
        status: "coming_soon",
        icon: "Linkedin",
      },
      {
        id: "industry-news-briefing",
        title: "Industry News Briefing",
        description: "Read, discuss, and react to current business news with executive vocabulary.",
        duration: "Ongoing",
        level: "B2+",
        sessions: 4,
        status: "coming_soon",
        icon: "Newspaper",
      },
      {
        id: "podcast-companion",
        title: "Podcast Companion",
        description: "Extract language, insights, and arguments from top business podcasts.",
        duration: "Ongoing",
        level: "C1",
        sessions: 4,
        status: "coming_soon",
        icon: "Podcast",
      },
    ],
  },
];
